/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import dominio.Comprador;
import dominio.Credencial;
import fachada.FachadaNegocio;
import fachada.IFachadaNegocio;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author santi
 */
public class frmLogin extends javax.swing.JFrame {

    private final IFachadaNegocio fachadaNegocio;

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.fachadaNegocio = new FachadaNegocio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        Registro = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        contrasenya = new javax.swing.JPasswordField();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(115, 46, 168));

        titulo.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Staem");

        iniciar_sesion.setBackground(new java.awt.Color(236, 211, 120));
        iniciar_sesion.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        iniciar_sesion.setForeground(new java.awt.Color(51, 51, 51));
        iniciar_sesion.setText("Iniciar sesion");
        iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_sesionActionPerformed(evt);
            }
        });

        registrarse.setBackground(new java.awt.Color(236, 211, 120));
        registrarse.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        registrarse.setForeground(new java.awt.Color(51, 51, 51));
        registrarse.setText("Registrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        usuario.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(153, 153, 153));
        usuario.setText("Usuario");
        usuario.setToolTipText("");
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usuario.setName(""); // NOI18N
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioFocusLost(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        Registro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("¿No tienes una cuenta?");

        inicio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("Inicio de sesión");

        contrasenya.setText("Contraseña");
        contrasenya.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrasenyaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contrasenyaFocusLost(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Staem.png"))); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(210, 210, 210)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Registro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(usuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasenya))
                        .addGap(18, 18, 18)
                        .addComponent(iniciar_sesion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(inicio))
                            .addComponent(titulo))
                        .addGap(300, 300, 300))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo)
                    .addComponent(logo))
                .addGap(22, 22, 22)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(inicio)
                        .addGap(37, 37, 37)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Registro)
                .addGap(18, 18, 18)
                .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        usuario.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_sesionActionPerformed

        try {
            Comprador consultarComprador = fachadaNegocio.consultarComprador(this.extaerDatos());
            if (consultarComprador != null) {
                frmTienda tiendita = new frmTienda();
                tiendita.setVisible(true);
                this.dispose();
            }

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar_sesionActionPerformed

    public Comprador extaerDatos() throws NoSuchAlgorithmException {
        Comprador comprador = new Comprador();
        comprador.setCredencial(new Credencial(this.usuario.getText(), this.contrasenya.getText()));
        return comprador;
    }
    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
        frmRegistarUsuario pantallaRegistroUsuario = new frmRegistarUsuario();
        pantallaRegistroUsuario.setVisible(true);
    }//GEN-LAST:event_registrarseActionPerformed

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        if (usuario.getText().equals("Usuario")) {
            usuario.setText("");
            usuario.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_usuarioFocusGained

    private void usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusLost
        if (usuario.getText().equals("")) {
            usuario.setText("Usuario");
            usuario.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_usuarioFocusLost

    private void contrasenyaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenyaFocusGained
        // TODO add your handling code here:
        if (contrasenya.getText().equals("Contraseña")) {
            contrasenya.setText("");
            contrasenya.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_contrasenyaFocusGained

    private void contrasenyaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenyaFocusLost
        // TODO add your handling code here:
        if (contrasenya.getText().equals("")) {
            contrasenya.setText("Contraseña");
            contrasenya.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_contrasenyaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registro;
    private javax.swing.JPasswordField contrasenya;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton iniciar_sesion;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel logo;
    private javax.swing.JButton registrarse;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
