/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import fachada.FachadaNegocio;
import fachada.IFachadaNegocio;
import java.awt.Color;
import dominio.Comprador;
import dominio.Credencial;
import dominio.Domicilio;
import java.security.NoSuchAlgorithmException;


/**
 *
 * @author santi
 */
public class frmRegistarUsuario extends javax.swing.JFrame {

    private final IFachadaNegocio fachadaNegocio;

    /**
     * Creates new form frmRegistarUsuario
     */
    public frmRegistarUsuario() {
        initComponents();
        this.fachadaNegocio = new FachadaNegocio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();
        contrasenya = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();
        aMaterno = new javax.swing.JTextField();
        aPaterno = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        codigoPostal = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(115, 46, 168));

        titulo.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Staem");

        Registro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("Registro de usuario");

        registrar.setBackground(new java.awt.Color(236, 211, 120));
        registrar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        usuario.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(153, 153, 153));
        usuario.setText("Usuario");
        usuario.setToolTipText("");
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usuario.setName(""); // NOI18N
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioFocusLost(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setText("Correo electronico");
        email.setToolTipText("");
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(236, 211, 120));
        Volver.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        Volver.setText("Volver a inicio");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        contrasenya.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        contrasenya.setForeground(new java.awt.Color(153, 153, 153));
        contrasenya.setText("Contraseña");
        contrasenya.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contrasenya.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrasenyaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contrasenyaFocusLost(evt);
            }
        });
        contrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenyaActionPerformed(evt);
            }
        });

        calle.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        calle.setForeground(new java.awt.Color(153, 153, 153));
        calle.setText("Calle");
        calle.setToolTipText("");
        calle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calle.setName(""); // NOI18N
        calle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                calleFocusLost(evt);
            }
        });
        calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleActionPerformed(evt);
            }
        });

        aMaterno.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        aMaterno.setForeground(new java.awt.Color(153, 153, 153));
        aMaterno.setText("Apellido materno");
        aMaterno.setToolTipText("");
        aMaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aMaterno.setName(""); // NOI18N
        aMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aMaternoFocusLost(evt);
            }
        });
        aMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMaternoActionPerformed(evt);
            }
        });

        aPaterno.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        aPaterno.setForeground(new java.awt.Color(153, 153, 153));
        aPaterno.setText("Apellido paterno");
        aPaterno.setToolTipText("");
        aPaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aPaterno.setName(""); // NOI18N
        aPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aPaternoFocusLost(evt);
            }
        });
        aPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPaternoActionPerformed(evt);
            }
        });

        nombres.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        nombres.setForeground(new java.awt.Color(153, 153, 153));
        nombres.setText("Nombres");
        nombres.setToolTipText("");
        nombres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nombres.setName(""); // NOI18N
        nombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresFocusLost(evt);
            }
        });
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        numero.setForeground(new java.awt.Color(153, 153, 153));
        numero.setText("Numero");
        numero.setToolTipText("");
        numero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero.setName(""); // NOI18N
        numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroFocusLost(evt);
            }
        });
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        codigoPostal.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        codigoPostal.setForeground(new java.awt.Color(153, 153, 153));
        codigoPostal.setText("Codigo Postal");
        codigoPostal.setToolTipText("");
        codigoPostal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        codigoPostal.setName(""); // NOI18N
        codigoPostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoPostalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoPostalFocusLost(evt);
            }
        });
        codigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Staem.png"))); // NOI18N

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Registro)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(215, 215, 215))
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57))))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registro)
                .addGap(41, 41, 41)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        try {
            fachadaNegocio.agregarComprador(this.extraerDatos());
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_registrarActionPerformed

    public Comprador extraerDatos() throws NoSuchAlgorithmException {
        Comprador comprador = new Comprador();
        Credencial credencial = new Credencial();
        Domicilio domicilio = new Domicilio();

        comprador.setEmail(this.email.getText());
        comprador.setNombres(this.nombres.getText());
        comprador.setaPaterno(this.aPaterno.getText());
        comprador.setaMaterno(this.aMaterno.getText());
        domicilio.setCalle(this.calle.getText());
        domicilio.setNumero(this.numero.getText());
        domicilio.setCodigoPostal(this.codigoPostal.getText());
        credencial.setUsuario(this.usuario.getText());
        credencial.setContrasenya(this.contrasenya.getText());
        comprador.setDomicilio(domicilio);
        comprador.setCredencial(credencial);

        return comprador;
    }


    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        if (usuario.getText().equals("Usuario")) {
            usuario.setText("");
            usuario.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_usuarioFocusGained

    private void usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusLost
        if (usuario.getText().equals("")) {
            usuario.setText("Usuario");
            usuario.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_usuarioFocusLost

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if (email.getText().equals("Correo electronico")) {
            email.setText("");
            email.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if (email.getText().equals("")) {
            email.setText("Correo electronico");
            email.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void contrasenyaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenyaFocusGained
        if (contrasenya.getText().equals("Contraseña")) {
            contrasenya.setText("");
            contrasenya.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_contrasenyaFocusGained

    private void contrasenyaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenyaFocusLost
        if (contrasenya.getText().equals("")) {
            contrasenya.setText("Contraseña");
            contrasenya.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_contrasenyaFocusLost

    private void contrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenyaActionPerformed

    private void calleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calleFocusGained
        if (calle.getText().equals("Calle")) {
            calle.setText("");
            calle.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_calleFocusGained

    private void calleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calleFocusLost
        if (calle.getText().equals("")) {
            calle.setText("Calle");
            calle.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_calleFocusLost

    private void calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleActionPerformed

    private void aMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aMaternoFocusGained
        if (aMaterno.getText().equals("Apellido materno")) {
            aMaterno.setText("");
            aMaterno.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_aMaternoFocusGained

    private void aMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aMaternoFocusLost
        if (aMaterno.getText().equals("")) {
            aMaterno.setText("Apellido materno");
            aMaterno.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_aMaternoFocusLost

    private void aMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aMaternoActionPerformed

    private void aPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aPaternoFocusGained
        if (aPaterno.getText().equals("Apellido paterno")) {
            aPaterno.setText("");
            aPaterno.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_aPaternoFocusGained

    private void aPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aPaternoFocusLost
        if (aPaterno.getText().equals("")) {
            aPaterno.setText("Apellido paterno");
            aPaterno.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_aPaternoFocusLost

    private void aPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPaternoActionPerformed

    private void nombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresFocusGained
        if (nombres.getText().equals("Nombres")) {
            nombres.setText("");
            nombres.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_nombresFocusGained

    private void nombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresFocusLost
        if (nombres.getText().equals("")) {
            nombres.setText("Nombres");
            nombres.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_nombresFocusLost

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void numeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusGained
        // TODO add your handling code here:
        if (numero.getText().equals("Numero")) {
            numero.setText("");
            numero.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_numeroFocusGained

    private void numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusLost
        // TODO add your handling code here:
        if (numero.getText().equals("")) {
            numero.setText("Numero");
            numero.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_numeroFocusLost

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void codigoPostalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoPostalFocusGained
        // TODO add your handling code here:
        if (codigoPostal.getText().equals("Codigo Postal")) {
            codigoPostal.setText("");
            codigoPostal.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_codigoPostalFocusGained

    private void codigoPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoPostalFocusLost
        // TODO add your handling code here:
        if (codigoPostal.getText().equals("")) {
            codigoPostal.setText("Codigo Postal");
            codigoPostal.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_codigoPostalFocusLost

    private void codigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Registro;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField aMaterno;
    private javax.swing.JTextField aPaterno;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JTextField contrasenya;
    private javax.swing.JTextField email;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField numero;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
